name: Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential qt6-base-dev libeigen3-dev
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
